### ISSUE TITLE
The UVC lib cant install

### ISSUE THREAD

**Issue by Danjuanlab** [joelpurra/node-uvc#3]
I use npm to install uvc,but shows code 128 .
```
C:\Users\zifan\Desktop\vue\test\electron-vite-vue>npm i uvc
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/node-ffi-libraries/node-ffi-library-libuvc-v0.0.6.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
```

And I try yarn to install ,but fail too~

**Comment by joelpurra** [comment]
@Danjuanlab: `package.json` uses generic `github:` urls for the `libuvc` dependency. Apparently this can cause issues for some `npm` versions/configurations.

- https://github.com/joelpurra/node-uvc/blob/v1.0.0/package.json#L18
- https://docs.npmjs.com/cli/v9/configuring-npm/package-json#github-urls

This type of url does not specify either `https:`, `ssh:`, nor `git+ssh:` urls -- it *should* use whatever is available. It seems that your `npm` is configured to use `ssh:` urls, but you have not authenticated with github. Either authenticate with (try `ssh -T github.com`) or configure `npm` to only use `https:` for `github:` urls.

- https://github.com/npm/cli/issues/2610
- https://stackoverflow.com/questions/61051073/npm-install-from-git-use-https-instead-ssh

While it may cause issues for you at this time, `github:` dependency urls are somewhat useful and quite flexible. I think they should stay as they are.

Does that fix the issue for you? If so, please close this issue.
